// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phimpuokavohoqdsqyde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaW1wdW9rYXZvaG9xZHNxeWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDIxMDMsImV4cCI6MjA3MTc3ODEwM30.sFdFg5vlimacN6e3UEaYiWXCV9V6uFvuyGKqsDdnzI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});